DATABASE = {
    "Which two traffic types use the Real-Time Transport Protocol (RTP)": ["video", "voice"],
    "Which wireless technology has low-power and data rate requirements making it popular in home automation applications": "ZigBee",
    "Which layer of the TCP/IP model provides a route to forward messages through an internetwork": "internet",
    "Which type of server relies on record types such as A, NS, AAAA, and MX in order to provide services": "DNS",
    "What are proprietary protocols": "protocols developed by organizations who have control over their definition and operation",
    "What service is provided by DNS": "Resolves domain names, such as cisco.com, into IP addresses.",
    "A client packet is received by a server. The packet has a destination port number of 110. What service is the client requesting": "POP3",
    "What command can be used on a Windows PC to see the IP configuration of that computer": "ipconfig",
    "A wired laser printer is attached to a home computer. That printer has been shared so that other computers on the home network can also use the printer. What networking model is in use": "peer-to-peer (P2P)",
    "What characteristic describes a virus": "malicious software or code running on an end device",
    "Three bank employees are using the corporate network. The first employee uses a web browser to view a company web page in order to read some announcements. The second employee accesses the corporate database to perform some financial transactions. The third employee participates in an important live audio conference with other corporate managers in branch offices. If QoS is implemented on this network, what will be the priorities from highest to lowest of the different data types": "audio conference, financial transactions, web page",
    "Match the description to the IPv6 addressing component. (Not all options are used.)": ["nx","ut","te"],
    " Refer to the exhibit. If Host1 were to transfer a file to the server, what layers of the TCP/IP model would be used": "as",
    " Match the characteristic to the forwarding method. (Not all options are used.)": ["hc", "mc", "bc"],
    "Refer to the exhibit. The IP address of which device interface should be used as the default gateway setting of host H1": "1G",
    "What service is provided by Internet Messenger": "ae",
    "Refer to the exhibit. Match the network with the correct IP address and prefix that will satisfy the usable host addressing requirements for each network.": ["a5","b6","c7","d0"],
    "Refer to the exhibit. Which protocol was responsible for building the table that is shown": "ARP",
    "A network administrator notices that some newly installed Ethernet cabling is carrying corrupt and distorted data signals. The new cabling was installed in the ceiling close to fluorescent lights and electrical equipment. Which two factors may interfere with the copper cabling and result in signal distortion and data corruption": ["RFI", "EMI"],
    "A host is trying to send a packet to a device on a remote LAN segment, but there are currently no mappings in its ARP cache. How will the device obtain a destination MAC address": "It will send an ARP request for the MAC address of the default gateway",
    "A client packet is received by a server. The packet has a destination port number of 53. What service is the client requesting": "DNS",
    "A network administrator is adding a new LAN to a branch office. The new LAN must support 25 connected devices. What is the smallest network mask that the network administrator can use for the new network": "255.255.255.224",
    "What characteristic describes a Trojan horse": "malicious software or code running on an end device",
    "What service is provided by HTTPS": "Uses encryption to secure the exchange of text, graphic images, sound, and video on the web.",
    "A technician with a PC is using multiple applications while connected to the Internet. How is the PC able to keep track of the data flow between multiple application sessions and have each application receive the correct packet flows": "Th.",
    "A network administrator is adding a new LAN to a branch office. The new LAN must support 61 connected devices. What is the smallest network mask that the network administrator can use for the new network": "255.255.255.192",
    "Refer to the exhibit. Match the network with the correct IP address and prefix that will satisfy the usable host addressing requirements for each network. (Not all options are used.)": ["a5","b6","c7","d0"],
    "What characteristic describes a DoS attack": "an attack that slows or crashes a device or network service",
    "Match the application protocols to the correct transport protocols.": ["ft","ht","st"],
    "What service is provided by SMTP": "Ar.",
    "Which scenario describes a function provided by the transport layer": "A student has two web browser windows open in order to access two web sites. The transport layer ensures the correct web page is delivered to the correct browser window.",
    "Refer to the exhibit. Host B on subnet Teachers transmits a packet to host D on subnet Students. Which Layer 2 and Layer 3 addresses are contained in the PDUs that are transmitted from host B to the router": "Ne",
    "What does the term “attenuation” mean in data communication": "loss of signal strength as distance increases",
    "Refer to the exhibit. An administrator is trying to configure the switch but receives the error message that is displayed in the exhibit. What is the problem": "ec",
    "Which two protocols operate at the top layer of the TCP/IP protocol suite": ["POP", "DNS"],
    "A company has a file server that shares a folder named Public. The network security policy specifies that the Public folder is assigned Read-Only rights to anyone who can log into the server while the Edit rights are assigned only to the network admin group. Which component is addressed in the AAA network service framework": "az",
    "What three requirements are defined by the protocols used in network communcations to allow message transmission across a network": ["message size", "message encoding", "delivery options"],
    "What are two characteristics of IP": ["does not require a dedicated end-to-end connection", "operates independently of the network media"],
    "An employee of a large corporation remotely logs into the company using the appropriate username and password. The employee is attending an important video conference with a customer concerning a large sale. It is important for the video quality to be excellent during the meeting. The employee is unaware that after a successful login, the connection to the company ISP failed. The secondary connection, however, activated within seconds. The disruption was not noticed by the employee or other employees. What three network characteristics are described in this scenario": ["security", "quality of service", "fault tolerance"],
    "What are two common causes of signal degradation when using UTP cabling": ["improper termination", "lr"],
    "Which subnet would include the address 192.168.1.96 as a usable host address": "192.168.1.64/26",
    "Refer to the exhibit. On the basis of the output, which two statements about network connectivity are correct": ["There are 4 hops between this device and the device at 192.168.100.1.", "There is connectivity between this device and the device at 192.168.100.1."],
    "Which two statements describe how to assess traffic flow patterns and network traffic types using a protocol analyzer": ["Capture traffic during peak utilization times to get a good representation of the different traffic types.", "Perform the capture on different network segments."],
    "What is the consequence of configuring a router with the ipv6 unicast-routing global configuration command": "The IPv6 enabled router interfaces begin sending ICMPv6 Router Advertisement messages.",
    "The IPv6 enabled router interfaces begin sending ICMPv6 Router Advertisement messages.": ["application", "session", "presentation"],
    " Refer to the exhibit. If PC1 is sending a packet to PC2 and routing has been configured between the two routers, what will R1 do with the Ethernet frame header attached by PC1": "remove the Ethernet header and configure a new Layer 2 header before sending it out S0/0/0",
    "What will happen if the default gateway address is incorrectly configured on a host": "The host cannot communicate with hosts in other networks.",
    "What are two features of ARP": ["Iy", "Ip"],
    "A network administrator is adding a new LAN to a branch office. The new LAN must support 90 connected devices. What is the smallest network mask that the network administrator can use for the new network": "18",
    "What are two ICMPv6 messages that are not present in ICMP for IPv4": ["Neighbor Solicitation", "Router Advertisement"],
    " A client packet is received by a server. The packet has a destination port number of 80. What service is the client requesting": "HTTP",
    "What is an advantage for small organizations of adopting IMAP instead of POP": "Messages are kept in the mail servers until they are manually deleted from the email client.",
    "A technician can ping the IP address of the web server of a remote company but cannot successfully ping the URL address of the same web server. Which software utility can the technician use to diagnose the problem": "nslookup",
    "Which two functions are performed at the LLC sublayer of the OSI Data Link Layer to facilitate Ethernet communication": ["em", "pe", "he", "aa"],
    "The global configuration command ip default-gateway 172.16.100.1 is applied to a switch. What is the effect of this command": "Tr.",
    " What happens when the transport input ssh command is entered on the switch vty lines": "Communication between the switch and remote users is encrypted.",
    "Match the type of threat with the cause. (Not all options are used.)": ["er","hd","ey","mg"],
    "A disgruntled employee is using some free wireless networking tools to determine information about the enterprise wireless networks. This person is planning on using this information to hack the wireless network. What type of attack is this": "reconnaissance",
    "What service is provided by HTTP": "A basic set of rules for exchanging text, graphic images, sound, video, and other multimedia files on the web.",
    "A client packet is received by a server. The packet has a destination port number of 67. What service is the client requesting": "DHCP",
    "What are two problems that can be caused by a large number of ARP request and reply messages": ["The ARP request is sent as a broadcast, and will flood the entire subnet.", "All ARP request messages must be processed by all nodes on the local network."],
    "A group of Windows PCs in a new subnet has been added to an Ethernet network. When testing the connectivity, a technician finds that these PCs can access local network resources but not the Internet resources. To troubleshoot the problem, the technician wants to initially confirm the IP address and DNS configurations on the PCs, and also verify connectivity to the local router. Which three Windows CLI commands and utilities will provide the necessary information": ["ping", "ipconfig", "nslookup"],
    "During the process of forwarding traffic, what will the router do immediately after matching the destination IP address to a network on a directly connected routing table entry": "switch the packet to the directly connected interface",
    "What characteristic describes antispyware": "applications that protect end devices from becoming infected with malicious software",
    "A network administrator needs to keep the user ID, password, and session contents private when establishing remote CLI connectivity with a switch to manage it. Which access method should be chosen": "SSH",
    "What are the two most effective ways to defend against malware": ["Update the operating system and other application software.", "Install and update antivirus software."],
    "Which type of security threat would be responsible if a spreadsheet add-on disables the local software firewall": "Trojan horse",
    "Which frame field is created by a source node and used by a destination node to ensure that a transmitted data signal has not been altered by interference, distortion, or signal loss": "fe",
    "A network administrator is adding a new LAN to a branch office. The new LAN must support 4 connected devices. What is the smallest network mask that the network administrator can use for the new network": "28",
    "What service is provided by POP3": "Retrieves email from the server by downloading the email to the local mail application of the client.",
    "What two security solutions are most likely to be used only in a corporate environment": ["virtual private networks", "intrusion prevention systems"],
    "What characteristic describes antivirus software": "applications that protect end devices from becoming infected with malicious software",
    "What mechanism is used by a router to prevent a received IPv4 packet from traveling endlessly on a network": "Id",
    "A client packet is received by a server. The packet has a destination port number of 69. What service is the client requesting": "TFTP",
    "An administrator defined a local user account with a secret password on router R1 for use with SSH. Which three additional steps are required to configure R1 to accept only encrypted SSH connections": ["Ce.", "gh.", "Eh."],
    "Which two functions are performed at the MAC sublayer of the OSI Data Link Layer to facilitate Ethernet communication": ["implements trailer with frame check sequence for error detection", "implements a process to delimit fields within an Ethernet 2 frame", "responsible for internal structure of Ethernet frame", "integrates Layer 2 flows between 10 Gigabit Ethernet over fiber and 1 Gigabit Ethernet over copper", "implements CSMA/CD over legacy shared half-duplex media", "applies delimiting of Ethernet frame fields to synchronize communication between nodes"],
    "An IPv6 enabled device sends a data packet with the destination address of FF02::2. What is the target of this packet": "all IPv6 configured",
    "What are the three parts of an IPv6 global unicast address": ["subnet ID", "global routing prefix", "interface ID"],
    "A network administrator is designing the layout of a new wireless network. Which three areas of concern should be accounted for when building a wireless network": ["interference", "security", "coverage area"],
    "A new network administrator has been asked to enter a banner message on a Cisco device. What is the fastest way a network administrator could test whether the banner is properly configured": "Exit privileged EXEC mode and press Enter.",
    "What method is used to manage contention-based access on a wireless network": "CSMA/CA",
    "What is a function of the data link layer": "provides for the exchange of frames over a common local medial",
    "What is the purpose of the TCP sliding window": "to request that a source decrease the rate at which it transmits data",
    "What characteristic describes spyware": "software that is installed on a user device and collects information about the user",
    "Which switching method drops frames that fail the FCS check": "store-and-forward switching",
    "Which range of link-local addresses can be assigned to an IPv6-enabled interface": "FE80::/10",
    "What service is provided by FTP": "Allows for data transfers between a client and a file server.",
    "A user is attempting to access http://www.cisco.com/ without success. Which two configuration values must be set on the host to allow this access": ["DNS server", "default gateway"],
    "Which two statements accurately describe an advantage or a disadvantage when deploying NAT for IPv4 in a network": ["NAT introduces problems for some applications that require end-to-end connectivity.", "Ns."],
    "What would be the interface ID of an IPv6 enabled interface with a MAC address of 1C-6F-65-C2-BD-F8 when the interface ID is generated by using the EUI-64 process": "E8",
    "Refer to the exhibit. PC1 issues an ARP request because it needs to send a packet to PC2. In this scenario, what will happen next": "PC2 will send an ARP reply with the PC2 MAC address.",
    "What service is provided by BOOTP": "Legacy application that enables a diskless workstation to discover its own IP address and find a BOOTP server on the network.",
    "What characteristic describes adware": "software that is installed on a user device and collects information about the user",
    "When a switch configuration includes a user-defined error threshold on a per-port basis, to which switching method will the switch revert when the error threshold is reached": "store-and-forward",
    "Match a statement to the related network model. (Not all options are used.)": ["nk","ck"],
    "What are two primary responsibilities of the Ethernet MAC sublayer": ["What are two primary responsibilities of the Ethernet MAC sublayer", "data encapsulation"],
    "Refer to the exhibit. What three facts can be determined from the viewable output of the show ip interface brief command": ["The switch can be remotely managedy", "One device is attached to a physical interface.", "The default SVI has been configuredn."],
    "Match each type of frame field to its function. (Not all options are used.)":["an","er","te","fl"] ,
    "What is the subnet ID associated with the IPv6 address 2001:DA48:FC5:A4:3D1B::1/64": "42",
    "Users are reporting longer delays in authentication and in accessing network resources during certain time periods of the week. What kind of information should network engineers check to find out if this situation is part of a normal network behavior": "the network performance baseline",
    "How does the service password-encryption command enhance password security on Cisco routers and switches": "It encrypts passwords that are stored in router or switch configuration files.",
    "Match the firewall function to the type of threat protection it provides to the network. (Not all options are used.)": "none",
    " Which two statements are correct in a comparison of IPv4 and IPv6 packet headers": ["sThe Source Address field name from IPv4 is kept in IPv6.", "The Time-to-Live field from IPv4 has been replaced by the Hop Limit field in IPv6."],
    "A network administrator wants to have the same network mask for all networks at a particular small site. The site has the following networks and number of devices:IP phones – 22 addresses PCs – 20 addresses needed Printers – 2 addresses needed Scanners – 2 addresses needed": "255.255.255.224",
    " What characteristic describes identity theft": "the use of stolen credentials to access private data",
    "A network administrator is adding a new LAN to a branch office. The new LAN must support 200 connected devices. What is the smallest network mask that the network administrator can use for the new network": "50",
    "What are three commonly followed standards for constructing and installing cabling": ["cable lengths", "pinouts", "connector types"],
    " Refer to the exhibit. What is wrong with the displayed termination": "The untwisted length of each wire is too long.",
    " Match the characteristic to the category.": ["3h","se","32"],
    "A client packet is received by a server. The packet has a destination port number of 143. What service is the client requesting": "IMAP",
    "What are two characteristics shared by TCP and UDP": ["port numbering", "use of checksum"],
    "Refer to the exhibit. Which two network addresses can be assigned to the network containing 10 hosts? Your answers should waste the fewest addresses, not reuse addresses that are already assigned, and stay within the 10.18.10.0/24 range of addresses": ["88", "48"],
    "A client packet is received by a server. The packet has a destination port number of 21. What service is the client requesting": "FTP",
    "What attribute of a NIC would place it at the data link layer of the OSI model": "MAC address",
    "A network administrator is adding a new LAN to a branch office. The new LAN must support 10 connected devices. What is the smallest network mask that the network administrator can use for the new network": "255.255.255.240",
    "What technique is used with UTP cable to help protect against signal interference from crosstalk": "twisting the wires together into pairso",
    "Refer to the exhibit. The network administrator has assigned the LAN of LBMISS an address range of 192.168.10.0. This address range has been subnetted using a /29 prefix. In order to accommodate a new building, the technician has decided to use the fifth subnet for configuring the new network (subnet zero is the first subnet). By company policies, the router interface is always assigned the first usable host address and the workgroup server is given the last usable host address. Which configuration should be entered into the properties of the workgroup server to allow connectivity to the Internet": "83",
    "Refer to the exhibit. The switches are in their default configuration. Host A needs to communicate with host D, but host A does not have the MAC address for its default gateway. Which network hosts will receive the ARP request sent by host A": "B, C, and router R1",
    "Match a statement to the related network model.": ["nk","dk"],
    "Refer to the exhibit. A network engineer has been given the network address of 192.168.99.0 and a subnet mask of 255.255.255.192 to subnet across the four networks shown. How many total host addresses are unused across all four subnets": "200",
    "Which connector is used with twisted-pair cabling in an Ethernet LAN": "rj45",
    "A client packet is received by a server. The packet has a destination port number of 22. What service is the client requesting": "SSH",
    "What characteristic describes an IPS": "a network device that filters access and traffic coming into a network",
    "What service is provided by DHCP": "Dynamically assigns IP addresses to end and intermediary devices.",
    "Match the header field with the appropriate layer of the OSI model.": ["82","f2","t3","s3"],
    "Refer to the exhibit. The switches have a default configuration. Host A needs to communicate with host D, but host A does not have the MAC address for the default gateway. Which network devices will receive the ARP request sent by host A":"b1",
    "Which wireless technology has low-power and low-data rate requirements making it popular in IoT environments": "Zigbee",
    "What two ICMPv6 message types must be permitted through IPv6 access control lists to allow resolution of Layer 3 addresses to Layer 2 MAC addresses": ["neighbor solicitations", "neighbor advertisements"],
    "A client is using SLAAC to obtain an IPv6 address for its interface. After an address has been generated and applied to the interface, what must the client do before it can begin to use this IPv6 address": "It must send an ICMPv6 Neighbor Solicitation message to ensure that the address is not already in use on the network.",
    "Two pings were issued from a host on a local network. The first ping was issued to the IP address of the default gateway of the host and it failed. The second ping was issued to the IP address of a host outside the local network and it was successful. What is a possible cause for the failed ping": "Security rules are applied to the default gateway device, preventing it from processing ping requests.",
    "An organization is assigned an IPv6 address block of 2001:db8:0:ca00::/56. How many subnets can be created without using bits in the interface ID space": "256",
    "What subnet mask is needed if an IPv4 network has 40 devices that need IP addresses and address space is not to be wasted": "255.255.255.192",
    "Refer to the exhibit. If host A sends an IP packet to host B, what will the destination address be in the frame when it leaves host A": "BB:BB:BB:BB:BB:BB",
    "What is a benefit of using cloud computing in networking": "Network capabilities are extended without requiring investment in new infrastructure, personnel, or software.",
    "Which two statements are correct about MAC and IP addresses during data transmission if NAT is not involved": ["Destination IP addresses in a packet header remain constant along the entire path to a target host.", "Destination and source MAC addresses have local significance and change every time a frame goes from one LAN to another."],
    "What is one main characteristic of the data link layer": "It shields the upper layer protocol from being aware of the physical medium to be used in the communication.",
    "What are three characteristics of the CSMA/CD process": ["A device listens and waits until the media is not busy before transmitting.", "After detecting a collision, hosts can attempt to resume transmission after a random time delay has expired.", "All of the devices on a segment see data that passes on the network medium."],
    "Which information does the show startup-config command display": "nm",
    "Which two commands can be used on a Windows host to display the routing table": ["route print", "netstat -r"],
    "What are two functions that are provided by the network layer": ["directing data packets to destination hosts on other networks", "providing end devices with a unique network identifier"],
    "Which two statements describe features of an IPv4 routing table on a router": ["It stores information about routes derived from the active router interfaces.", "If a default static route is configured in the router, an entry will be included in the routing table with source code S.", "The routing table stores information about routes derived from the active router interfaces."],
    "What characteristic describes a VPN": "a tunneling protocol that provides remote users with secure access into the network of an organization",
    "Why would a Layer 2 switch need an IP address": "to enable the switch to be managed remotelyd",
    "Match each description to its corresponding term. (Not all options are used.)":["nt","gk","gn"],
    "A user sends an HTTP request to a web server on a remote network. During encapsulation for this request, what information is added to the address field of a frame to indicate the destination": "MAC address of the default gateway",
    "What is an advantage to using a protocol that is defined by an open standard": "It encourages competition and promotes choices.",
    "Data is being sent from a source PC to a destination server. Which three statements correctly describe the function of TCP or UDP in this situation": ["The source port field identifies the running application or service that will handle data returning to the PC.", "UDP segments are encapsulated within IP packets for transport across the network.", "The UDP destination port number identifies the application or service on the server which will handle the data."],
    "Match each description with the corresponding TCP mechanism.": ["ne","us","mn","rt"],
    "Refer to the exhibit. A company uses the address block of 128.107.0.0/16 for its network. What subnet mask would provide the maximum number of equal size subnets while providing enough host addresses for each subnet in the exhibit": "255.255.255.128",
    "A network administrator wants to have the same subnet mask for three subnetworks at a small site. The site has the following networks and numbers of devices": "4255.255.255.240",
    "Match each item to the type of topology diagram on which it is typically identified.":"im",
    "What two pieces of information are displayed in the output of the show ip interface brief command": ["IP addresses", "Layer 1 statuses"],
    "A user is complaining that an external web page is taking longer than normal to load.The web page does eventually load on the user machine. Which tool should the technician use with administrator privileges in order to locate where the issue is in the network": "tracert",
    "Which value, that is contained in an IPv4 header field, is decremented by each router that receives a packet": "Time-to-Live",
    "A network technician is researching the use of fiber optic cabling in a new technology center. Which two issues should be considered before implementing fiber optic media": ["Fiber optic cabling requires different termination and splicing expertise from what copper cabling requiresr", "Fiber optic provides higher data capacity but is more expensive than copper cablingr"],
    "Match each description with an appropriate IP address.": ["e5","l5","p2","l1"],
    "A user is executing a tracert to a remote device. At what point would a router, which is in the path to the destination device, stop forwarding the packet": "TTL",
    "Users report that the network access is slow. After questioning the employees, the network administrator learned that one employee downloaded a third-party scanning program for the printer. What type of malware might be introduced that causes slow performance of the network": "worm",

    
    "A client packet is received by a server. The packet has a destination port number of 22. What service is the client requesting?":"ssh",
    "Refer to the exhibit. What does the value of the window size specify": "the amount of data that can be sent before an acknowledgment is required",
    "To which TCP port group does the port 414 belong": "well-known",
    "What is a user trying to determine when issuing a ping 10.1.1.1 command on a PC": "if there is connectivity with the destination devicen",
    "Match the descriptions to the terms. (Not all options are used.)":["gg","cs","ke","sr"],
    "What is a characteristic of a switch virtual interface (SVI)": "An SVI is created in software and requires a configured IP address and a subnet mask in order to provide remote access to the switch.",
    "What happens when a switch receives a frame and the calculated CRC value is different than the value that is in the FCS field": "ds",
    "Two network engineers are discussing the methods used to forward frames through a switch. What is an important concept related to the cut-through method of switching": "Packets can be relayed with errors when fast-forward switching is used.",
    "Which two issues can cause both runts and giants in Ethernet networks": ["half-duplex operations", "a malfunctioning NIC"],
    "Which two commands could be used to check if DNS name resolution is working properly on a Windows PC": ["nslookup cisco.com", "ping cisco.com"],
    "A small advertising company has a web server that provides critical business service. The company connects to the Internet through a leased line service to an ISP. Which approach best provides cost effective redundancy for the Internet connection": "Add a connection to the Internet via a DSL line to another ISP.",
    "Refer to the exhibit. A network administrator is connecting a new host to the Registrar LAN. The host needs to communicate with remote networks. What IP address would be configured as the default gateway on the new host": "34",
    "Match the command with the device mode at which the command is entered.": ["sg","e>","le","if"],
    "A router boots and enters setup mode. What is the reason for this": "The configuration file is missing from NVRAM.",
    "Two students are working on a network design project. One student is doing the drawing, while the other student is writing the proposal. The drawing is finished and the student wants to share the folder that contains the drawing so that the other student can access the file and copy it to a USB drive. Which networking model is being used": "peer-to-peer",
    "Which command is used to manually query a DNS server to resolve a specific host name": "nslookup",
    "Which PDU is processed when a host computer is de-encapsulating a message at the transport layer of the TCP/IP model": "segment",
    "Which two OSI model layers have the same functionality as two layers of the TCP/IP model": ["network", "transport"],
    "Which three layers of the OSI model are comparable in function to the application layer of the TCP/IP model": ["presentation", "application", "session"],
    "Network information. What task might a user be trying to accomplish by using the ping 2001:db8:FACE:39::10 command": "verifying that there is connectivity to the internet",
    "Which two ICMP messages are used by both IPv4 and IPv6 protocols": ["protocol unreachable", "route"],
    "A network technician types the command ping 127.0.0.1 at the command prompt on a computer. What is the technician trying to accomplish": "testing the integrity of the TCP/IP stack on the local machine",
    "Although CSMA/CD is still a feature of Ethernet, why is it no longer necessary": "the use of full-duplex capable Layer 2",
    "What does a router do when it receives a Layer 2 frame over the network medium": "de-encapsulates the frame",
    "Which two acronyms represent the data link sublayers that Ethernet relies upon to operate": ["LLC", "MAC"],
    "A network team is comparing topologies for connecting on a shared media. Which physical topology is an example of a hybrid topology for a LAN": "extended star",
    "Given network 172.18.109.0, which subnet mask would be used if 6 host bits were available": "92",
    "Three devices are on three different subnets. Match the network address and the broadcast address with each subnet where these devices are located.": ["14","32",],
    "What type of address is 198.133.219.162": "public",
    "What does the IP address 192.168.1.15/29 represent": "broadcast address",
    "Why is NAT not needed in IPv6": "Any host or user can get a public IPv6 network address because the number of available IPv6 addresses is extremely large.",
    "What routing table entry has a next hop address associated with a destination network": "remote routes",
    "Which term describes a field in the IPv4 packet header that contains a unicast, multicast, or broadcast address": "destination IPv4 address",
    "If the default gateway is configured incorrectly on the host, what is the impact on communications": "te.",
    "Which is the compressed format of the IPv6 address fe80:0000:0000:0000:0220:0b3f:f0e0:0029": "fe80::220:b3f:f0e0:29",
    "Refer to the exhibit. A user issues the command netstat –r on a workstation. Which IPv6 address is one of the link-local addresses of the workstation": "fe80::30d0:115:3f57:fe4c/128",
    "What type of IPv6 address is represented by ::1/128": "loopback",
    "Which statement describes network security": "ers.",
    "Which two devices would be described as intermediary devices": ["wireless LAN controller", "IPS"],
    "Refer to the exhibit. The exhibit shows a small switched network and the contents of the MAC address table of the switch. PC1 has sent a frame addressed to PC3. What will the switch do with the frame": "The switch will forward the frame to all ports except port 4.",
    "Which destination address is used in an ARP request frame": "FFFF.FFFF.FFFF",
    "Refer to the exhibit. PC1 issues an ARP request because it needs to send a packet to PC3. In this scenario, what will happen next": "00",
    "A network administrator is issuing the login block-for 180 attempts 2 within 30 command on a router. Which threat is the network administrator trying to prevent": "a user who is trying to guess a password to access the router",
    "Which statement describes the characteristics of packet-filtering and stateful firewalls as they relate to the OSI model": "packet-filtering firewall typically can filter up to the transport layer, whereas a stateful firewall can filter up to the session layer.",
    "What are two ways to protect a computer from malware": ["Use antivirus software.", "Keep software up to date."],
    "The employees and residents of Ciscoville cannot access the Internet or any remote web-based services. IT workers quickly determine that the city firewall is being flooded with so much traffic that a breakdown of connectivity to the Internet is occurring. Which type of attack is being launched at Ciscoville": "DoS",
    "Which two statements describe the characteristics of fiber-optic cabling": ["Fiber-optic cabling does not conduct electricity.", "Fiber-optic cabling is primarily used as backbone cabling."],
    "What OSI physical layer term describes the measure of the transfer of bits across a medium over a given period of time": "throughput",
    "Refer to the exhibit. What is the maximum possible throughput between the PC and the server":"28",
    "Match the description with the media.": "None",

}
